import Navbar from '@/components/Navbar';
import '../styles/globals.css'
import Footer from '@/components/Footer';
import Totop from '@/components/Totop';

export const metadata = {
  title: 'Leerhuis_Nextjs_3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <Navbar />
          {children}
          <Footer />
        </main>

        <Totop />
      </body>
    </html>
  );
}
