import Navbar from '@/components/Navbar';
import '../styles/globals.css'

export const metadata = {
  title: 'Leerhuis_Nextjs_3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="app">{children}</main>
      </body>
    </html>
  );
}
