import Navbar from './components/Navbar';
import './globals.css'
import Footer from './components/Footer';
import Totop from './components/Totop';
import GetData from './getdata/page';
export const metadata = {
  title: 'Leerhuis_Nextjs_3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <Navbar>
            <GetData />
          </Navbar>
         {children}
          <Footer />
        </main>

        <Totop />
      </body>
    </html>
  );
}
